#pragma once

const int BUTTON_WIDTH = 300;
const int BUTTON_HEIGHT = 200;
const int BUTTON_TOTAL = 4;

enum KeyPresses
{
	ANY_KEY,
	UP_ARROW,
	DOWN_ARROW,
	LEFT_ARROW,
	RIGHT_ARROW,
	TOTAL
};

enum Lbuttonsprite
{
	BUTTON_SPRITE_MOUSE_OUT,
	BUTTON_SPRITE_MOUSE_OVER_MOTION,
	BUTTON_SPRITE_MOUSE_DOWN,
	BUTTON_SPRITE_MOUSE_UP,
	BUTTON_SPRITE_TOTAL
};